"""
L-DINO-CoT Image Generation Script

Generates images using L-VQA optimized diffusion for evaluation.
Loads prompts from JSON file generated by lvqas_data_gen.py.

Usage:
    python run_hd_lvqa.py --json lvqa_prompts.json --output eval_images --num_per_prompt 3
"""

import torch
import t2v_metrics
import os
import json
import argparse
import sys
import traceback
from pipelines.pipeline_sd_dinot import StableDiffusionDiNOTPipeline

# Supported Stable Diffusion models
SD_MODELS = {
    "v1.4": "CompVis/stable-diffusion-v1-4",
    "v1.5": "runwayml/stable-diffusion-v1-5",
    "v2.0": "Manojb/stable-diffusion-2-base",
    "v2.1": "Manojb/stable-diffusion-2-1-base",
    "v2.2": "stabilityai/stable-diffusion-2-1", # v2.1-768 is often what people mean by 2.2/2.1 updated
}

# Supported VQA models
ALL_VQA_MODELS = [
    "clip-flant5-xl",
    "llava-v1.5-13b",
    "sharegpt4v-13b",
    "instructblip-flant5-xl",
]

torch.cuda.empty_cache()

# Force unbuffered output for real-time logging
sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', buffering=1)

# Parse arguments
parser = argparse.ArgumentParser(description="Generate L-VQA optimized images for evaluation")
parser.add_argument("--json", "-j", type=str, default="lvqa_prompts.json",
                    help="JSON file with decomposed prompts (from lvqas_data_gen.py)")
parser.add_argument("--output", "-o", type=str, default="lvqa_eval_images_test",
                    help="Output directory for generated images")
parser.add_argument("--num_per_prompt", "-n", type=int, default=1,
                    help="Number of images to generate per prompt")
parser.add_argument("--seed", "-s", type=int, default=33,
                    help="Base random seed")
parser.add_argument("--start_idx", type=int, default=0,
                    help="Start index in prompts list")
parser.add_argument("--max_prompts", type=int, default=None,
                    help="Maximum number of prompts to process")
parser.add_argument("--epochs", "-e", type=int, default=2,
                    help="Number of optimization epochs")
parser.add_argument("--inference_steps", type=int, default=50,
                    help="Number of inference steps")
parser.add_argument("--sd_device", type=str, default="cuda:0",
                    help="Device for Stable Diffusion")
parser.add_argument("--vqa_device", type=str, default="cuda:1",
                    help="Device for VQA model")
parser.add_argument("--sd_model", type=str, default="v1.4", choices=list(SD_MODELS.keys()),
                    help="Stable Diffusion model version to use")
parser.add_argument("--vqa_model", type=str, default="clip-flant5-xl", choices=ALL_VQA_MODELS,
                    help="VQA model to use for scoring")
parser.add_argument("--no_ldino", action="store_true",
                    help="Disable L-DINO-CoT (simpler generation, less memory)")

args = parser.parse_args()

# Setup devices
sd_device = args.sd_device
vqa_model_device = args.vqa_device

print(f"[Setup] Loading Stable Diffusion {args.sd_model} on {sd_device}")
model_id = SD_MODELS[args.sd_model]
pipe = StableDiffusionDiNOTPipeline.from_pretrained(model_id)
pipe.to(sd_device)

print(f"[Setup] Loading VQA model {args.vqa_model} on {vqa_model_device}")
vqa_model = t2v_metrics.VQAScore(model=args.vqa_model, device=vqa_model_device)  # XL works, XXL causes OOM
pipe.init_vqa_model(vqa_model, vqa_model_device)

# Generator
generator = torch.Generator(device=sd_device).manual_seed(args.seed)

# Load prompts from JSON
if os.path.exists(args.json):
    print(f"[Data] Loading prompts from {args.json}")
    with open(args.json, 'r') as f:
        data = json.load(f)
    
    if "prompts" in data:
        prompts = data["prompts"]
    else:
        # Handle list format
        prompts = data if isinstance(data, list) else []
    
    print(f"[Data] Loaded {len(prompts)} prompts")
else:
    print(f"[Error] JSON file not found: {args.json}")
    sys.exit(1)

# Determine range
start_idx = args.start_idx
end_idx = len(prompts)
if args.max_prompts is not None:
    end_idx = min(start_idx + args.max_prompts, len(prompts))

print(f"[Run] Processing prompts {start_idx} to {end_idx}")
print(f"[Run] Generating {args.num_per_prompt} images per prompt")
print(f"[Run] Output directory: {args.output}")

# Create output directory
os.makedirs(args.output, exist_ok=True)

# Track results
results = {
    "config": {
        "seed": args.seed,
        "num_per_prompt": args.num_per_prompt,
        "optimization_epochs": args.epochs,
        "inference_steps": args.inference_steps
    },
    "images": []
}

# Generate images
for idx in range(start_idx, end_idx):
#    if idx < 48:
#        continue
    data = prompts[idx]
    prompt = data['prompt']
    
    print(f"\n{'='*60}")
    print(f"[{idx+1}/{end_idx}] Prompt: {prompt}")
    print(f"{'='*60}")
    
    # Create prompt-specific subdirectory
    safe_prompt = prompt.replace(" ", "_").replace("/", "_")[:50]
    prompt_dir = os.path.join(args.output, f"{idx:03d}_{safe_prompt}")
    os.makedirs(prompt_dir, exist_ok=True)
    
    for i in range(args.num_per_prompt):
        current_seed = args.seed + idx * args.num_per_prompt + i
        generator.manual_seed(current_seed)
        
        print(f"\n  [Image {i+1}/{args.num_per_prompt}] seed={current_seed}")
        
        pipeline_args = {
            "prompt": prompt,
            "dependency_graph": data.get('dependency_graph', None),
            "num_inference_steps": args.inference_steps,
            "generator": generator,
            "optimization_epoch": args.epochs
        }
        
        # L-DINO-CoT: Enable localized VQA unconditionally unless disabled by flag
        if not args.no_ldino:
            pipeline_args["use_localized_vqa"] = True
        
        try:
            output = pipe(**pipeline_args)
            images = output.images
            image = images[0] if isinstance(images, list) else images
            
            # Save image
            out_filename = f"seed_{current_seed}.png"
            out_path = os.path.join(prompt_dir, out_filename)
            image.save(out_path)
            print(f"  ✓ Saved: {out_path}")
            
            # Track result
            results["images"].append({
                "prompt": prompt,
                "seed": current_seed,
                "path": out_path,
                "prompt_idx": idx,
                "image_idx": i
            })
            
        except Exception as e:
            print(f"  ✗ Error: {e}")
            traceback.print_exc()
            results["images"].append({
                "prompt": prompt,
                "seed": current_seed,
                "path": None,
                "error": str(e),
                "prompt_idx": idx,
                "image_idx": i
            })
        
        # Aggressive memory cleanup to prevent OOM
        import gc
        gc.collect()
        torch.cuda.empty_cache()
        gc.collect()
    
    # Extra cleanup after each prompt
    import gc
    gc.collect()
    torch.cuda.empty_cache()

# Save results manifest
manifest_path = os.path.join(args.output, "manifest.json")
with open(manifest_path, 'w') as f:
    json.dump(results, f, indent=2)
print(f"\n[Done] Saved manifest to {manifest_path}")

print(f"\n{'='*60}")
print(f"Generation complete!")
print(f"  Total prompts: {end_idx - start_idx}")
print(f"  Total images: {len([r for r in results['images'] if r.get('path')])}")
print(f"  Output directory: {args.output}")
print(f"{'='*60}")
